[target.thumbv7em-none-eabihf]
# deveboxx stm32h7xx board uses Cortex-M7
runner = 'probe-run --chip STM32H743VI'
# blackpill board uses Cortex-M4 with FPU
#runner = 'probe-run --chip STM32F411CEUx'
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=--nmagic",
]

# bluepill board uses Cortex-M3
[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8T6"
rustflags = [
    "-C", "link-arg=-Tdefmt.x",
]

[build]
# cortex-m4 and up
target = "thumbv7em-none-eabihf"
# cortex-m3
#target = "thumbv7m-none-eabi"
# cortex-m0
#target = "thumbv6m-none-eabi"

[env]
#DEFMT_LOG = "trace"
DEFMT_LOG = "info"
